up:
	docker-compose -f ./connectors/docker-compose.yaml up -d
down:
	docker-compose -f ./connectors/docker-compose.yaml down
up-nginx:
	docker-compose -f ./nginx/docker-compose.yaml up -d
down-nginx:
	docker-compose -f ./nginx/docker-compose.yaml down
